[project]
name = "prob-gen-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "notebook>=7.4.7",
    "pylint>=4.0.2",
    "pyright>=1.1.407",
]
