run_name: "cuda_large"  # Custom run name for output folder
training:
  batch_size: 512       # A100 has huge VRAM, feed it!
  learning_rate: 0.0005 # Lower LR for stability with large batches
  epochs: 100           # Let it converge fully

model:
  vae:
    latent_dim: 256     # High capacity to store "Lane markings", "Traffic Signs"
  rnn:
    hidden_size: 512    # Increased capacity for complex dynamics
    num_layers: 2       # Stacked LSTM for better context

data:
  # High resolution. Divisible by 16. 
  # Captures distant objects which reduces drift.
  img_height: 192       
  img_width: 640