run_name: "model_emil_z128"  # Custom run name for output folder
training:
  batch_size: 128       # Good balance for ~6600 images
  learning_rate: 0.0001
  epochs: 100           # Full training

model:
  vae:
    latent_dim: 128     # Balanced capacity
  rnn:
    hidden_size: 512
    num_layers: 2

data:
  img_height: 192
  img_width: 640