run_name: "default_run"

vae:
  latent_dim: 64
  sequence_length: 1     # Moved from data
  training:
    batch_size: 32
    learning_rate: 1e-3
    epochs: 100

rnn:
  hidden_size: 256
  num_layers: 1
  sequence_length: 5     # Moved from data
  training:
    batch_size: 32
    learning_rate: 1e-3
    epochs: 100

data:
  path: "data/kitti"
  pose_path: "data/kitti/poses"
  test_sequences: ["09", "10"]
  # img_size: 128
  img_height: 128
  img_width: 416

visualization:
  save_every: 10
  num_samples: 8