run_name: "default_run"  # Custom run name for output folder

vae:
  latent_dim: 128
  sequence_length: 1     # Moved from data
  training:
    batch_size: 256
    learning_rate: 1e-3
    epochs: 100

rnn:
  hidden_size: 256
  num_layers: 1
  sequence_length: 5     # Moved from data
  training:
    batch_size: 512
    learning_rate: 1e-3
    epochs: 100
  
    
data:
  # Maintains 3.25:1 ratio, very fast to process
  img_height: 128       
  img_width: 416

